lib: zstd: Add back `EXPORT_SYMBOL`s that were removed in b96ee8420335d504c1ac577d50a87ab3624124a4
Fix for:
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - ZSTD_CStreamWorkspaceBound
 - ZSTD_DStreamWorkspaceBound
 - ZSTD_compressStream
 - ZSTD_decompressStream
 - ZSTD_endStream
 - ZSTD_getParams
 - ZSTD_initCStream
 - ZSTD_initDStream
 - ZSTD_maxCLevel

Change-Id: Id2dcdb09a9a771c5800dab73eaf412fe63b21c2f